import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import {
  generateAnalysisPDF,
  type ReportData,
  type ReportCheck,
} from "@/lib/pdf-generator";
import { sendReportEmail } from "@/lib/email-service";
import { notifyNewLead } from "@/lib/notification-service";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

/* ------------------------------------------------------------------ */
/* Helpers                                                            */
/* ------------------------------------------------------------------ */

function normalizeStatus(raw: unknown): "pass" | "fail" | "warning" {
  if (typeof raw !== "string") return "warning";
  const s = raw.toLowerCase();
  if (s === "pass" || s === "passed" || s === "ok" || s === "good" || s === "true")
    return "pass";
  if (s === "fail" || s === "failed" || s === "error" || s === "bad" || s === "false")
    return "fail";
  if (s === "warning" || s === "warn" || s === "caution") return "warning";
  return "warning";
}

function coerceChecks(raw: any): ReportCheck[] {
  if (!Array.isArray(raw)) return [];

  return raw
    .map((item: any): ReportCheck | null => {
      if (!item || typeof item !== "object") return null;

      const name = String(item.name || item.label || "Check").trim();
      const description = String(
        item.description || item.detail || item.message || ""
      ).trim();

      let status: "pass" | "fail" | "warning";
      if (typeof item.status === "string") {
        status = normalizeStatus(item.status);
      } else if (typeof item.passed === "boolean") {
        status = item.passed ? "pass" : "fail";
      } else if (typeof item.severity === "string") {
        const sev = item.severity.toLowerCase();
        if (sev === "high") status = "fail";
        else if (sev === "medium") status = "warning";
        else status = "pass";
      } else {
        status = "warning";
      }

      const category = String(item.category || "General").trim();

      return { category, name, status, description };
    })
    .filter((c): c is ReportCheck => c !== null);
}

function coerceScores(raw: any) {
  const out: {
    performance?: number;
    seo?: number;
    overall?: number;
    visibility?: number;
  } = {};
  if (!raw || typeof raw !== "object") return out;

  const pick = (k: string) => {
    const v = raw[k];
    if (typeof v === "number" && isFinite(v)) out[k as keyof typeof out] = Math.round(v);
  };

  pick("performance");
  pick("seo");
  pick("overall");
  pick("visibility");

  if (out.performance === undefined && typeof raw.performanceScore === "number")
    out.performance = Math.round(raw.performanceScore);
  if (out.seo === undefined && typeof raw.seoScore === "number")
    out.seo = Math.round(raw.seoScore);
  if (out.overall === undefined && typeof raw.overallScore === "number")
    out.overall = Math.round(raw.overallScore);
  if (out.visibility === undefined && typeof raw.visibilityScore === "number")
    out.visibility = Math.round(raw.visibilityScore);

  return out;
}

function buildSummary(raw: any, url: string, toolName: string): string {
  if (typeof raw === "string" && raw.trim()) return raw.trim();
  const s = coerceScores(raw?.scores || raw);
  const overall = s.overall ?? s.performance ?? s.seo;
  if (typeof overall === "number") {
    if (overall >= 70)
      return `${toolName}: ${url} scored ${overall}/100 overall — solid foundation with room to optimize. The detailed checks below highlight the highest-impact improvements.`;
    if (overall >= 40)
      return `${toolName}: ${url} scored ${overall}/100 overall — several opportunities detected. Addressing the failing checks below will deliver the fastest ranking and speed gains.`;
    return `${toolName}: ${url} scored ${overall}/100 overall — significant issues found that are likely hurting your search visibility and conversion rate. We recommend a priority remediation sprint.`;
  }
  return `Analysis report for ${url} generated by SOCIAL VIENS ${toolName}.`;
}

function buildRecommendations(raw: any, checks: ReportCheck[]): string[] {
  if (Array.isArray(raw) && raw.length > 0) {
    return raw
      .map((r: any) => (typeof r === "string" ? r : r?.text || r?.title || ""))
      .filter((s: string) => s.trim().length > 0)
      .slice(0, 12);
  }

  const failed = checks.filter((c) => c.status === "fail").slice(0, 6);
  if (failed.length > 0) {
    return failed.map((c) => `Fix: ${c.name} — ${c.description}`);
  }

  return [
    "Improve page load speed by optimizing images and enabling compression.",
    "Add unique, descriptive meta descriptions to every page.",
    "Implement structured data (JSON-LD) for rich search results.",
    "Optimize for mobile-first indexing with a responsive layout.",
  ];
}

/* ------------------------------------------------------------------ */
/* POST handler                                                       */
/* ------------------------------------------------------------------ */

export async function POST(request: NextRequest) {
  try {
    let body: any;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
    }

    const { name, email, phone, url, toolName, analysisData, scores, source } =
      body || {};

    // Validate required fields
    if (!name || typeof name !== "string" || !name.trim()) {
      return NextResponse.json(
        { error: "Missing required field: name" },
        { status: 400 }
      );
    }
    if (!email || typeof email !== "string" || !email.includes("@")) {
      return NextResponse.json(
        { error: "Missing or invalid required field: email" },
        { status: 400 }
      );
    }
    if (!url || typeof url !== "string" || !url.trim()) {
      return NextResponse.json(
        { error: "Missing required field: url" },
        { status: 400 }
      );
    }
    if (!toolName || typeof toolName !== "string" || !toolName.trim()) {
      return NextResponse.json(
        { error: "Missing required field: toolName" },
        { status: 400 }
      );
    }

    // 1. Save lead to database (non-fatal if it fails)
    try {
      const lead = await db.lead.create({
        data: {
          name: String(name).trim(),
          email: String(email).trim(),
          phone: phone ? String(phone).trim() : "",
          message: `${toolName} report request for ${url}`,
          source:
            source ||
            `analysis-tool-${toolName}`.toLowerCase().replace(/\s+/g, "-"),
          status: "new",
        },
      });

      // Fire-and-forget: notify admin about the new lead (non-fatal).
      // Don't await so the report-generation flow stays fast.
      notifyNewLead(lead).catch((e) =>
        console.error("[/api/report] notification error:", e)
      );
    } catch (dbError) {
      console.error("[/api/report] DB error (non-fatal):", dbError);
      // Continue — still generate + email the report
    }

    // 2. Build ReportData
    const coercedScores = coerceScores(scores || analysisData?.scores);
    const checks = coerceChecks(
      analysisData?.checks || analysisData?.performanceChecks || []
    ).concat(
      coerceChecks(analysisData?.seoChecks || []).map((c) => ({
        ...c,
        category: c.category === "General" ? "SEO" : c.category,
      }))
    );

    const summary = buildSummary(analysisData, url, toolName);
    const recommendations = buildRecommendations(
      analysisData?.recommendations || analysisData?.quickWins,
      checks
    );

    const reportData: ReportData = {
      toolName,
      url,
      analyzedAt: new Date(),
      scores: coercedScores,
      checks,
      summary,
      recommendations,
    };

    // 3. Generate PDF
    let pdfBuffer: Buffer;
    try {
      pdfBuffer = await generateAnalysisPDF(reportData);
    } catch (pdfErr) {
      console.error("[/api/report] PDF generation error:", pdfErr);
      return NextResponse.json(
        {
          error: "Failed to generate PDF report",
          details: pdfErr instanceof Error ? pdfErr.message : String(pdfErr),
        },
        { status: 500 }
      );
    }

    // 4. Send email with PDF attachment
    const reportFilename = `SOCIAL-VIENS-${toolName
      .replace(/[^a-zA-Z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .toUpperCase()}-Report.pdf`;

    const emailResult = await sendReportEmail({
      to: String(email).trim(),
      name: String(name).trim(),
      reportBuffer: pdfBuffer,
      reportFilename,
      toolName,
      url,
    });

    // 5. Build WhatsApp link
    const whatsappMessage = encodeURIComponent(
      `Hi! I'm ${name}. I just used the ${toolName} on your website. I'd like a detailed report for ${url}.`
    );
    const whatsappUrl = `https://wa.me/918178004800?text=${whatsappMessage}`;

    return NextResponse.json({
      success: true,
      message: "Report generated and emailed successfully",
      whatsappUrl,
      emailPreviewUrl: emailResult.previewUrl,
      emailSent: emailResult.success,
      emailProvider: emailResult.provider,
      emailError: emailResult.error,
      reportSizeBytes: pdfBuffer.length,
    });
  } catch (error: any) {
    console.error("[/api/report] Error:", error);
    return NextResponse.json(
      {
        error: "Failed to generate report",
        details: error?.message || String(error),
      },
      { status: 500 }
    );
  }
}
